# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
#
# If you want to be able to access a string config[:site_title], for example:
#
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#
# 'name' is the name that appears in the edit form
#
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
#
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
#
# Some Examples:
#
site_title:
  name: Site Title
  default: "Children's Future International"

site_strapline:
  name: Site Strapline
  default: Student Records

site_color_background:
  name: Background Colour Hex
  default: "#cfb0c2"

site_color_menu:
  name: Menu Colour Hex
  default: "#873967"

programme_member_label:
  name: Programme member label
  default: "student"

show_courses:
  name: Show the courses tab?
  default: true
  type: boolean

default_url_for_emails:
  name: What is the first part of the URL for this site?
  default: "cfi.heroku.com"

default_url_for_emails_for_staging:
  name: What is the first part of the URL for the demo site?
  default: "cfi-staging.heroku.com"
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
#
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password
